app: cuddly-octo-palm-tree
ginMode: debug
httpPort: 3001
dbConftemp:
  dsn: sqlserver://sa:yourStrong(!)Password@localhost:1433?database=master
  maxIdleConns: 50
  maxOpenConns: 100
dbConf:
  dsn: host=192.168.0.61 user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
  maxIdleConns: 50
  maxOpenConns: 100